addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                 % "1.4.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.4.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"                  % "2.2.1")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("com.dwijnand"       % "sbt-dynver"                % "4.0.0")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                   % "1.1.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"              % "3.9.3")
// Scala-js support
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.1.0")
