object Versions {
  val slf4jVersion                  = "1.7.36"
  val slf4j2Version                 = "2.0.16"
  val logbackVersion                = "1.2.13"
  val logback2Version               = "1.4.12"
  val scalaCollectionCompatVersion  = "2.12.0"
  val logstashLogbackEncoderVersion = "6.6"
  val scalaJavaTimeVersion          = "2.6.0"
  val zioMetricsConnectorsVersion   = "2.3.1"
  val zioConfig                     = "4.0.3"
  val zioParser                     = "0.1.11"
  val zioPrelude                    = "1.0.0-RC36"
  val zioHttp                       = "3.0.1"
  val log4jVersion                  = "2.24.3"
}
